AllCops:
  TargetRubyVersion: 2.7

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Severity: 'warning'

Metrics/MethodLength:
  CountComments: false
  Max: 100

Metrics/ModuleLength:
  # These use file-spanning module blocks, making this cop useless
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 50

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
  Enabled: false

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*/**/*_spec.rb'

Style/SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

# Disabled since it catches strftime incorrectly
# See https://github.com/bbatsov/rubocop/issues/5245
Style/FormatStringToken:
  Enabled: false

# safe_load is too restrictive, since we need ERB
Security/YAMLLoad:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
